<?php

return array (
    'name' => '智慧同城生活平台',
    'beian' => '',
    'cdnurl' => '',
    'version' => '1.0.25',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'languages' =>
        array (
            'backend' => 'zh-cn',
            'frontend' => 'zh-cn',
        ),
    'fixedpage' => 'dashboard',
    'categorytype' =>
        array (
            'information' => '同城分类',
            'merchant' => '商户分类',
        ),
    'configgroup' =>
        array (
            'basic' => '基础配置',
            'email' => '邮件配置',
            'dictionary' => '字典配置',
            'user' => '会员配置',
            'wechat_pay' => '微信支付配置',
            'mini_wechat' => '微信小程序配置',
            'miniappSubscribeMessage' => '小程序订阅消息模板',
            'qy_wechat' => '企业微信配置',
            'qy_wechat_app1' => '企业微信_微信客服',
            'alioss' => '阿里云对象存储',
            'baidu_ai' => '百度AI开放平台',
            'alisms' => '阿里云短信平台',
        ),
    'mail_type' => '1',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_smtp_port' => '465',
    'mail_smtp_user' => '10000',
    'mail_smtp_pass' => 'password',
    'mail_verify_type' => '2',
    'mail_from' => '10000@qq.com',
    'attachmentcategory' =>
        array (
            'category1' => '分类一',
            'category2' => '分类二',
            'custom' => '自定义',
        ),
    'miniapp_appid' => 'XXXXXX',
    'miniapp_secret' => 'XXXXXX',
    'wechat_pay_mch_id' => 'XXXXXX',
    'wechat_pay_key_v2' => 'XXXXXX',
    'wechat_pay_cert_client' => '/uploads/20220416/cc1faf4355ae2348d09c60529bb8eb6a.pem',
    'wechat_pay_cert_key' => '/uploads/20220416/ad2f98ca9151d969693b7e28893375d8.pem',
    'baseImgUrl' => 'https://yktc.wangyunzhi.cn/',
    'is_auto_approve' => '1',
    'qy_wechat_corpid' => 'XXXXXX',
    'qy_wechat_app1_token' => 'XXXXXX',
    'qy_wechat_app1_encodingAESKey' => 'XXXXXX',
    'qy_wechat_app1_secret' => 'XXXXXX',
    'alioss_region' => 'yktc-oss.ipv4net.com',
    'alioss_accessKeyId' => 'XXXXXX',
    'alioss_accessKeySecret' => 'XXXXXX',
    'alioss_city_value' => 'cn-chengdu',
    'alioss_roleArn' => 'XXXXXX',
    'alioss_bucket' => 'yukuaitongcheng',
    'baidu_ai_appid' => '26085514',
    'baidu_ai_appKey' => 'XXXXXX',
    'baidu_ai_secretKey' => 'XXXXXX',
    'alioss_sms_accessKeyId' => 'XXXXXX',
    'alioss_sms_accessKeySecret' => 'XXXXXX',
    'alioss_sms_city_value' => 'cn-chengdu',
    'miniSubMsg_information_approve' => '4c-AkTnwd6-XXXXXX-Rr-L0kvU',
    'miniSubMsg_community_approve' => 'XXXXXX',
    'user_sms_upper_limit' => '3',
);
